from app.ml_model.predict_ai import analyze_expense

test_records = [
    "đặt tiền học thêm 300k",
    "mua sách công nghệ 150k",
    "tiền điện tháng này 1tr5",
    "uống cà phê 40k",
    "đi xe ôm về nhà 50k",
    "mua laptop mới 15 triệu",
    "thuê xe máy đi du lịch 200k",
    "sắm đồ cho văn phòng 500k",
    "chi phí đổ xăng 100k",
    "mua áo quần 300k",
    "thuê xe ô tô đi công tác 1tr",
    "tiền phòng trọ 2 triệu",
    "đi taxi đến văn phòng 80k",
    "đi xem phim với bạn 100k",
    "cà phê sáng 30k",
    "mua vé máy bay 2 triệu",
    "tiền internet tháng này 200k",
    "tiền wifi 150k",
    "mua sắm đồ thể thao 600k",
    "học phí tháng này 1 triệu",
    "tiền gas 250k",
    "đi du lịch Nhật Bản 15 triệu",
    "cắt tóc 50k",
    "massage 400k",
    "trả tiền internet 220k",
    "mua túi xách 300k",
    "tiền điện 1tr",
    "mua quần áo 350k",
    "mua sách 100k",
    "đi xe bus 15k",
    "thưởng tháng này 2tr",
    "mua quà tặng sinh nhật 500k",
    "tiền nhà 3 triệu",
    "đi học thêm 100k",
    "đặt món ăn ngoài 70k",
    "đi xe máy 20k",
    "mua giày thể thao 800k",
    "mua đồ linh tinh 50k",
    "tiền sinh hoạt tháng này 2 triệu",
    "chi tiêu cho quà tặng 100k",
    "tiền điện thoại 200k",
    "mua đồng hồ 1tr5",
    "tặng quà sinh nhật 300k",
    "mua đồ online 400k",
    "thưởng cuối năm 5 triệu",
    "đi công tác TP.HCM 1tr5",
    "tiền nhà tháng này 6 triệu",
    "mua sách cho con 200k",
    "cảm ơn thầy cô 150k",
    "thuê phòng khách sạn 800k",
    "trả tiền phòng trọ 2 triệu",
    "học phí cho khóa học online 1tr",
    "mua sắm đồ cho bếp 500k",
    "thuê xe ô tô 2 triệu",
    "mua kính mắt 300k",
    "chuyến bay đến Hà Nội 2 triệu",
    "tiền phí quản lý chung cư 400k",
    "mua phụ kiện điện thoại 100k",
    "mua điện thoại mới 5 triệu",
    "mua sắm đồ ăn nhanh 50k",
    "đi xe ôm đến sân bay 250k",
    "mua quà cho mẹ 500k",
    "mua quà tặng sinh nhật 100k",
    "tiền bảo hiểm xe 200k",
    "đi chơi với bạn 150k",
]

for t in test_records:
    print(t, "=>", analyze_expense(t))