from app.ml_model.predict_ai import analyze_expense

tests = [
    "ăn sáng 25k",
    "ăn trưa cơm văn phòng 50k",
    "cf sáng 30k",
    "trà sữa trân châu 60k",
    "uống nước ép 35k",
    "ăn tối lẩu 200k",
    "ăn vặt khoai chiên 15k",
    "đổ xăng 70k",
    "grab đi làm 50k",
    "taxi về nhà 90k",
    "gửi xe tháng 100k",
    "rửa xe 30k",
    "bảo dưỡng xe 200k",
    "thuê xe máy 250k",
    "vé tàu 300k",
    "mua áo khoác 500k",
    "mua quần jeans 400k",
    "shopping skincare 700k",
    "mua laptop 15tr",
    "mua tai nghe bluetooth 400k",
    "tiền điện 1tr",
    "tiền nước tháng này 200k",
    "trả tiền internet 220k",
    "tiền nhà 5tr",
    "tiền gas 250k",
    "cắt tóc 50k",
    "massage 400k",
    "spa 500k",
    "mua thuốc cảm 80k",
    "đi khám bệnh 300k",
    "mừng cưới 500k",
    "nạp thẻ 100k",
    "học phí tháng này 1tr5",
    "chi tiêu linh tinh 100k",
    "tiêu vặt 50k",
    "ăn sáng bánh mì 15k",
    "cf với bạn 40k",
    "uống latte 60k",
    "ăn tối pizza 120k",
    "shopping đồ điện tử 2tr",
    "mua đồng hồ 1tr2",
    "tiền điện nước 1tr5",
    "tiền phòng trọ tháng này 3tr",
    "đi xe bus 10k",
    "xe ôm sân bay 300k",
    "mua đồ online 250k",
    "đi du lịch 1tr",
    "tặng quà 250k",
    "mua sách 150k",
    "ăn sáng bún 25k",
    "grab chiều 45k"
]

for t in tests:
    print(t, "=>", analyze_expense(t))